name: "Publish manually next stable version"

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi-publish
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.7"

      - name: Bump to stable
        run: uv version --bump stable

      - name: Build
        run: uv build --clear

      - name: Publish
        run: uv publish

      - name: Add tag for easier navigation
        run: |
          PROJECT_VERSION="$(uv version --short)"
          git tag -a $(PROJECT_VERSION) -m $(PROJECT_VERSION)

      - name: Commit and push changes
        run: |
          PROJECT_VERSION="$(uv version --short)"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml
          git add uv.lock
          git commit -m "Update version to ${PROJECT_VERSION} and publish to pypi"
          git push origin main --tags
